predict_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "predict_app"
urlpatterns = [
    path('' , views.index , name="index"),
    path('system/' , views.predict_system , name="system"),
    path('result/' , views.predict_system_result , name="result"),
    path('about/' , views.about, name="about")


]

predict_project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('predict_app/' , include('predict_app.urls'))
]

predict_app/models.py
from django.db import models

# Create your models here.

predict_app/views.py
from django.shortcuts import render
from .predict_disease import predict_heart_disease
# Create your views here.


def index(request):
    return render(request , 'predict_app/index.html')


def predict_system(request):
    context = {'message':"See Patient's Result Here!" , 'class': 'alert-info' }
    return render(request ,'predict_app/predict_system.html' , context)

def predict_system_result(request):
    data = request.POST


    age= float(data.get('age'))
    sex= float(data.get('gender'))
    cp= float(data.get('cp'))
    trtbps =  float(data.get('trestbps'))
    chol =  float(data.get('chol'))
    fbs =  float(data.get('fbs'))
    restecg = float(data.get('restecg'))
    thalach =  float(data.get('thalach'))
    exng =  float(data.get('exang'))
    oldpeak =float(data.get('oldpeak'))
    slp = float(data.get('slope'))
    ca = float(data.get('ca'))
    thal = float(data.get('thal'))
    new_data =  [ age , sex , cp , trtbps , chol , fbs , restecg , thalach, exng , oldpeak , slp , ca, thal]

    result = predict_heart_disease(new_data)
    if result == False:
        message = "Patient Do Not Seems to have issue related to heart disease, you may proceed to other diagnostic measures!"
        cl = "alert-success"
    else:
        message = "Patient Might be in danger of heart disease, please proceed to other diagnostic measures immediately!"
        cl = "alert-danger"

    context = {
    'result': result ,
     'message': message ,
     'class': cl ,
     'firstname': data.get('firstname'),
     'lastname' : data.get('lastname'),
     'address': data.get('address'),
     'sex' :  data.get('gender')
     }


    # print(request.POST.get('ca'))
    return render(request , 'predict_app/result.html' , context)



def about(request):
    return render(request , 'predict_app/about.html')

templates/predict_app/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About Project Work | Disease Prediction System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container-fluid">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Disease Prediction System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"   id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'predict_app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'predict_app:system' %}">Use System</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About Project</a>
            </li>

          </ul>
        </div>
      </nav>


      <div class="container row col-12">

        <div class="result col-12">
          <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h3 class="display-5">About Patient's Disease Prediction System</h3>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-12" style="padding: 20px;">




        </div>




        <div class="result col-lg-6 col-md-6 col-sm-12">
          <div class="alert {{ class }}" role="alert">
            {{ message }}
          </div>
        </div>


      </div>





    </div>
  </body>
</html>

templates/predict_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Disease Prediction System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Disease Prediction System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"   id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'predict_app:system' %}">Use System</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'predict_app:about' %}">About Project</a>
            </li>

          </ul>
        </div>
      </nav>


      <div class="result col-12">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 class="display-5"> Patient's Disease Prediction System</h1>

          </div>
        </div>
      </div>

      <div class=" row col-12" style="margin-top: 50px; margin-bottom: 20px; padding: 50px;">

          <div class="text col-lg-6 col-md-6 col-sm-12 pt-30" style="padding: 20px;" >


              <h3>A Project
              By
              Olapade Ajoke Victoria
              164495</h3>


          </div>

          <div class="img col-lg-6 col-md-6 col-sm-12" >
            <div class="col-12 col-sm-12">
              <img height="auto" width="100%" src="{% static 'imgs/heart-banner.svg'  %}" alt="banner">
            </div>
          </div>

      </div>

      <div class="text-center" style="height: 200px;">
        <a href="{% url 'predict_app:system' %}" type="button" class="btn btn-primary btn-lg">Lauch System</a>
      </div>
    </div>
  </body>
</html>

templates/predict_app/predict_system.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Disease Prediction System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container-fluid">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Disease Prediction System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"   id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'predict_app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Use System</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'predict_app:about' %}">About Project</a>
            </li>

          </ul>
        </div>
      </nav>


      <div class="container row col-12">

        <div class="result col-12">
          <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-5"> Patient Disease Prediction System</h1>
              <p class="lead">
                <div class="result col-lg-6 col-md-6 col-sm-12">
                  <div class="alert {{ class }}" role="alert">
                    please fill the form below carefully
                  </div>
                </div>

              </p>
            </div>
          </div>
        </div>

        <div class="form col-lg-6 col-md-6 col-sm-12" style="padding: 20px;">

          <h3>Patient's Biodata</h3>


          <form action="{% url 'predict_app:result' %}" method="post" style="margin-bottom: 200px;">
            {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputEmail4">First Name</label>
                <input type="text" name="firstname" class="form-control" id="inputEmail4" placeholder="First Name">
              </div>
              <div class="form-group col-md-6">
                <label for="inputPassword4">Last Name</label>
                <input type="text" name="lastname" class="form-control" id="inputPassword4" placeholder="Last Name">
              </div>
            </div>
            <div class="form-group">
              <label for="inputAddress">Address</label>
              <input type="text" name="address" class="form-control" id="inputAddress" placeholder="1234 Main St">
            </div>

            <div class="form-group">
              <label for="inputAddress">Age</label>
              <input name="age" max="120" min="1" required type="number" step="0.1" class="form-control" id="inputAddress" placeholder="Age">
            </div>

            <div class="form-group">
              <label for="inputAddress">Gender  (Male = 1 , Female = 0)</label>
              <input min="0" max="1" name="gender" required type="number" step="0.1" class="form-control" id="inputAddress" placeholder="Male Or Female [1/0]">
            </div>

            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputCity">City</label>
                <input type="text" class="form-control" id="inputCity">
              </div>
              <div class="form-group col-md-4">
                <label for="inputState">State (Optional)</label>
                <select id="inputState" class="form-control">
                  <option selected>Choose...</option>
                  <option>...</option>
                </select>
              </div>

              <div class="form-group col-md-2">
                <label for="inputZip">Zip</label>
                <input type="text" class="form-control" id="inputZip">
              </div>
            </div>

            <hr>
            <h3>Patient's Medical Report</h3>

            <div class="form-group">
              <label for="inputAddress2">CP </label>
              <input name="cp" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="Chest Pain Type">
            </div>

            <div class="form-group">
              <label for="inputAddress2">TrestBps</label>
              <input name="trestbps"  type="number" required class="form-control" id="inputAddress2" placeholder="Resting blood pressure (in mm Hg on admission to the hospital) ">
            </div>

            <div class="form-group">
              <label for="inputAddress2">Chol</label>
              <input name="chol" type="number" required class="form-control" id="inputAddress2" placeholder="Serum cholestoral in mg/dl">
            </div>

            <div class="form-group">
              <label for="inputAddress2">Fasting blood sugar > 120 mg/dl (1 = true; 0 = false) </label>
              <input name="fbs" min="0" max="1" type="number" required class="form-control" id="inputAddress2" placeholder="Fbs">
            </div>

            <div class="form-group">
              <label for="inputAddress2"> Restecg (normal=0 / depression= 1)</label>
              <input name="restecg" min="0" max="1" type="number" required class="form-control" id="inputAddress" placeholder="Resting electrocardiographic results">
            </div>


            <div class="form-group">
              <label for="inputAddress2">Thalach</label>
              <input name="thalach" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="Maximum heart rate achieved ">
            </div>


            <div class="form-group">
              <label for="inputAddress2">Exang  (1 = yes; 0 = no) </label>
              <input name="exang"  min="0" max="1" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="Exercise induced angina">
            </div>

            <div class="form-group">
              <label for="inputAddress2">Oldpeak</label>
              <input name="oldpeak" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="ST depression induced by exercise relative to rest ">
            </div>


            <div class="form-group">
              <label for="inputAddress2">Slope (1: up-sloping / 2: flat / 3: down-sloping)</label>
              <input  name="slope" min="0" max="3" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="The slope of the peak exercise ST segment">
            </div>

            <div class="form-group">
              <label for="inputAddress2">CA number of major vessels (0–3) colored by fluoroscope </label>
              <input name="ca"  min="0" max="3" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="Ca">
            </div>

            <div class="form-group" >
              <label for="inputAddress2"> Thal  3 = normal; 6 = fixed defect; 7 = reversible defect </label>
              <input name="thal"  min="0" max="7" type="number" step="0.1" required class="form-control" id="inputAddress2" placeholder="Thal">
            </div>

            <button type="submit" class="btn btn-primary"> Predict Disease</button>
          </form>


        </div>



      </div>





    </div>
  </body>
</html>

templates/predict_app/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Disease Prediction System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript">
        function printResult(){
          window.print();
        }
    </script>


  </head>
  <body>
    <div class="container-fluid">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Disease Prediction System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"   id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'predict_app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'predict_app:system' %}">Use System</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'predict_app:about' %}">About Project</a>
            </li>

          </ul>
        </div>
      </nav>


      <div class="container col col-12" style="padding: 50px;">

        <div class="result col-12">
          <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-5"> Patient's Result </h1>
              <p class="lead">This is a project research work.</p>
            </div>
          </div>
        </div>

        <div class="form col-lg-6 col-md-6 col-sm-12" style="padding: 20px;">

          <h3>Patient's Biodata</h3>
          <div class="alert alert-secondary" role="alert">
              <h6>Full name: </h6>
              <p>{{ firstname }}  {{ lastname }}</p>
          </div>

          <div class="alert alert-secondary" role="alert">
              <h6>Gender (Male: 1 , Female: 0) : </h6>
              <p>{{ sex}}  </p>
          </div>

          <div class="alert alert-secondary" role="alert">
              <h6>Address: </h6>
              <p>{{ address }}  </p>
          </div>

        </div>


        <div class="result col-lg-6 col-md-6 col-sm-12">
            <h6>System's Remark</h6>
          <div class="alert {{ class }}" role="alert">
            {{ message }}
          </div>
        </div>

        <div class="text-center">
          <button  class="btn btn-success btn-md" onclick="printResult()">Print Result</button>
        </div>









      </div>





    </div>
  </body>

</html>